services:
  db:
    image: postgres:16
    container_name: arktech_db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  web:
    build:
      context: .
    container_name: arktech_web
    command: >
      sh -c "python manage.py migrate &&
             gunicorn arktech_blog.wsgi:application --bind 0.0.0.0:8000 --workers 4"
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db

volumes:
  postgres_data: